name: Reusable action of building snapshot and publish

on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
      github_tag:
        required: false
        type: string
    secrets:
      MAVEN_SIGNING_KEY_BASE64:
        required: false
      MAVEN_SIGNING_PASSPHRASE:
        required: false
      MAVEN_CENTRAL_USERNAME:
        required: false
      MAVEN_CENTRAL_PASSWORD:
        required: false
jobs:
  run_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle-v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean all modules
      run: ./gradlew cleanAllModules
    - name: ${{ inputs.action }}
      env:
        MAVEN_SIGNING_KEY_BASE64: ${{ secrets.MAVEN_SIGNING_KEY_BASE64 }}
        MAVEN_SIGNING_PASSPHRASE: ${{ secrets.MAVEN_SIGNING_PASSPHRASE }}
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      run: GITHUB_TAG=${{ inputs.github_tag }} ./gradlew ${{ inputs.action }}
